sugarcube-2:
  macros:
    keyOption:
      name: keyOption
    keyAction:
      name: keyAction
      container: true
    addMinutes:
      name: addMinutes
    addHours:
      name: addHours
    cash:
      name: cash
    unlessEmergency:
      name: unlessEmergency
      container: true
    workOption:
      name: workOption
    updateVariables:
      name: updateVariables
    scenery:
      name: scenery
    newmeter:
      name: newmeter
      container: true
    label:
      name: label
    colors:
      name: colors
    showmeter:
      name: showmeter
    popup:
      name: popup
    dialog:
      name: dialog
      container: true
    npcInteraction:
      name: npcInteraction
    sizing:
      name: sizing
    itemImage:
      name: itemImage
    openNpcInteraction:
      name: openNpcInteraction
    emoji:
      name: emoji
    sleep:
      name: sleep
    userEditListVar:
      name: userEditListVar
    npcGenderSymbol:
      name: npcGenderSymbol
    wanderingSlaves:
      name: wanderingSlaves
    personHunting:
      name: personHunting
    npcAddressPlayer:
      name: npcAddressPlayer
    sleepOption:
      name: sleepOption
    npcStimulated:
      name: npcStimulated
    slaveEvents:
      name: slaveEvents
    printPersonLink:
      name: printPersonLink
    npcStats:
      name: npcStats
    showCookFeedingRules:
      name: showCookFeedingRules
    thirdPerson:
      name: thirdPerson
    playerSay:
      name: playerSay
    npcSay:
      name: npcSay
    takeClothes:
      name: takeClothes
    dialogclose:
      name: dialogclose
    storeProductList:
      name: storeProductList
