sugarcube-2:
  macros:
    keyOption:
      name: keyOption
    addMinutes:
      name: addMinutes
    addHours:
      name: addHours
    cash:
      name: cash
    unlessLateToJob:
      name: unlessLateToJob
      container: true
    workOption:
      name: workOption
    updateVariables:
      name: updateVariables
    scenery:
      name: scenery
    newmeter:
      name: newmeter
      container: true
    label:
      name: label
    colors:
      name: colors
    showmeter:
      name: showmeter
    popup:
      name: popup
    dialog:
      name: dialog
      container: true
